[2024-01-01T11:55:51.127-0300] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: postgres_operator.fetch_pageviews manual__2024-01-01T14:55:40.723096+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
